### ISSUE TITLE
Table doesn't show in custom layout

### ISSUE THREAD

**Issue by megachester** [catalyst-team/mlcomp#29]
When I try to add table to my layout, e.g. 
```   
layout:
  - type: panel
    title: table
    items:
      - type: table
        source: [loss, mAP]
``` 

nothing shows up in report.

**Comment by lightforever** [comment]
Could you provide me please with the full layout? What is the version of MLComp?

**Comment by megachester** [comment]
Layout:
```
metric:
  name: mAP
  minimize: False

items:
  loss:
    type: series
    key: loss
  clf_loss:
    type: series
    key: clf_loss
  reg_loss:
    type: series
    key: reg_loss
  mAP:
    type: series
    key: mAP

layout:
  - type: panel
    title: table
    table: True
    parent_cols: 1
    items:
      - type: table
        source: [loss, mAP]

  - type: panel
    title: main
    parent_cols: 2
    row_height: 400
    items:
      - type: series
        source: loss
        multi: True
      - type: series
        source: mAP
        multi: True
      - type: series
        source: _other
```

Version is `20.3.1`
